# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\";\n\x15RegisterWorkerRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nworld_rank\x18\x02 \x01(\x05\"-\n\x13RegisterWorkerReply\x12\x16\n\x0enode_addresses\x18\x03 \x03(\t\"Z\n\x1cRegisterWorkerServiceRequest\x12\x12\n\nworld_rank\x18\x01 \x01(\x05\x12\x11\n\tworker_ip\x18\x02 \x01(\t\x12\x13\n\x0bworker_port\x18\x03 \x01(\x05\"I\n\x1aRegisterWorkerServiceReply\x12\x13\n\x0bray_address\x18\x01 \x01(\t\x12\x16\n\x0eredis_password\x18\x02 \x01(\t\")\n\x08\x46unction\x12\x0f\n\x07\x66unc_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x66unc\x18\x02 \x01(\x0c\"E\n\x0e\x46unctionResult\x12\x12\n\nworld_rank\x18\x01 \x01(\x05\x12\x0f\n\x07\x66unc_id\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\x0c\"\x07\n\x05\x45mpty2\xd3\x01\n\rDriverService\x12>\n\x0eRegisterWorker\x12\x16.RegisterWorkerRequest\x1a\x14.RegisterWorkerReply\x12S\n\x15RegisterWorkerService\x12\x1d.RegisterWorkerServiceRequest\x1a\x1b.RegisterWorkerServiceReply\x12-\n\x12RegisterFuncResult\x12\x0f.FunctionResult\x1a\x06.Empty2I\n\rWorkerService\x12 \n\x0bRunFunction\x12\t.Function\x1a\x06.Empty\x12\x16\n\x04Stop\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REGISTERWORKERREQUEST']._serialized_start=17
  _globals['_REGISTERWORKERREQUEST']._serialized_end=76
  _globals['_REGISTERWORKERREPLY']._serialized_start=78
  _globals['_REGISTERWORKERREPLY']._serialized_end=123
  _globals['_REGISTERWORKERSERVICEREQUEST']._serialized_start=125
  _globals['_REGISTERWORKERSERVICEREQUEST']._serialized_end=215
  _globals['_REGISTERWORKERSERVICEREPLY']._serialized_start=217
  _globals['_REGISTERWORKERSERVICEREPLY']._serialized_end=290
  _globals['_FUNCTION']._serialized_start=292
  _globals['_FUNCTION']._serialized_end=333
  _globals['_FUNCTIONRESULT']._serialized_start=335
  _globals['_FUNCTIONRESULT']._serialized_end=404
  _globals['_EMPTY']._serialized_start=406
  _globals['_EMPTY']._serialized_end=413
  _globals['_DRIVERSERVICE']._serialized_start=416
  _globals['_DRIVERSERVICE']._serialized_end=627
  _globals['_WORKERSERVICE']._serialized_start=629
  _globals['_WORKERSERVICE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
